---
driver:
  name: vagrant

# Fall back to 'chef_zero' as we are using a Policyfile to resolve external
# cookbooks
provisioner:
  name: chef_zero

# To use the InSpec Verifier, add a verifier block, and use `inspec`, that's it!
verifier:
  name: inspec

platforms:
  - name: ubuntu-15.04
    # This is a temporary measure before kitchen-vagrant uses Bento boxes
    # directly from Atlas.
    driver:
      box: bento/ubuntu-15.04
      box_url: null
  - name: centos-7.1
    # This is a temporary measure before kitchen-vagrant uses Bento boxes
    # directly from Atlas.
    driver:
      box: bento/centos-7.1
      box_url: null

suites:
  - name: default
    run_list:
      - recipe[inspec_example]
