name 'inspec_example'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures inspec_example'
long_description 'Installs/Configures inspec_example'
version '0.1.0'
